library("data.table")
library("ggplot2")
library("umap")
library("Rtsne")
library("locStra")
library("Matrix")
library("scales")
library("lubridate")
library("stringr")
library("RColorBrewer")
library("dplyr")
library("plyr")
library("immunarch")


set.seed(20)

kusnadi <- fread("kusnadi_VDJ_metadata.txt")
write.table(kusnadi, "kusnadi_VDJ_metadata_reformatted.txt", quote = F, sep = "\t", row.names = F)
lia <- fread("liao_VDJ_metadata.txt")
write.table(lia, "liao_VDJ_metadata_reformatted.txt", quote = F, sep = "\t", row.names = F)
zhang <- fread("zhang_VDJ_metadata.txt")
write.table(zhang, "zhang_VDJ_metadata_reformatted.txt", quote = F, sep = "\t", row.names = F)
wen <- fread("wen_VDJ_metadata.txt")
write.table(wen, "wen_VDJ_metadata_reformatted.txt", quote = F, sep = "\t", row.names = F)